"""Data models for smart wallet tracking and copy-trading strategies.

References:
- Polymarket Data API trades: https://docs.polymarket.com/api-reference/trade/get-trades
- Polymarket Data API positions: https://polymarket-data.com/data/positions
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


class Side(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class StrategyType(str, Enum):
    COPY = "copy"       # Follow smart wallets
    INVERSE = "inverse"  # Trade against smart wallets


class OrderType(str, Enum):
    MAKER = "maker"  # Limit order (better fill, no taker fee)
    TAKER = "taker"  # Market order (instant fill, taker fee)


@dataclass(frozen=True)
class Trade:
    """Single trade from Polymarket Data API."""
    trade_id: str
    market_id: str
    condition_id: str
    slug: str
    title: str
    outcome: str
    outcome_index: int
    side: Side
    price: float
    size: float  # in shares
    timestamp: int  # unix epoch seconds
    maker_address: str
    taker_address: str
    transaction_hash: str
    fee_rate_bps: int = 30

    @property
    def size_usd(self) -> float:
        return self.price * self.size

    @property
    def dt(self) -> datetime:
        return datetime.utcfromtimestamp(self.timestamp)


@dataclass
class WalletProfile:
    """Aggregated profile for a wallet address."""
    address: str
    total_volume_usd: float = 0.0
    total_pnl_usd: float = 0.0
    win_rate: float = 0.0
    num_markets: int = 0
    num_trades: int = 0
    avg_trade_size_usd: float = 0.0
    largest_trade_usd: float = 0.0
    first_seen: Optional[datetime] = None
    last_seen: Optional[datetime] = None
    # Derived scoring
    consistency_score: float = 0.0  # 0-1, how consistently profitable
    volume_score: float = 0.0       # normalized volume ranking
    edge_score: float = 0.0         # estimated edge per trade
    composite_score: float = 0.0    # combined smart money score

    @property
    def age_days(self) -> Optional[float]:
        if self.first_seen and self.last_seen:
            return (self.last_seen - self.first_seen).total_seconds() / 86400
        return None

    @property
    def trades_per_day(self) -> Optional[float]:
        age = self.age_days
        if age and age > 0:
            return self.num_trades / age
        return None


@dataclass
class CopySignal:
    """Signal generated by smart wallet activity."""
    wallet: WalletProfile
    trade: Trade
    strategy: StrategyType
    confidence: float  # 0-1
    target_price: float
    target_size_usd: float
    reason: str
    timestamp: datetime = field(default_factory=datetime.utcnow)


@dataclass
class BacktestTrade:
    """Record of a simulated trade in backtesting."""
    signal: CopySignal
    entry_price: float
    exit_price: Optional[float] = None
    entry_time: Optional[datetime] = None
    exit_time: Optional[datetime] = None
    size_usd: float = 0.0
    realized_pnl: Optional[float] = None
    slippage_cost: float = 0.0
    fee_cost: float = 0.0
    latency_ms: float = 0.0
    status: str = "open"  # open, closed, expired


@dataclass
class BacktestResult:
    """Aggregated backtest performance."""
    strategy: StrategyType
    start_date: datetime
    end_date: datetime
    initial_bankroll: float
    final_bankroll: float
    total_trades: int
    winning_trades: int
    losing_trades: int
    win_rate: float
    total_pnl: float
    total_return_pct: float
    max_drawdown_pct: float
    sharpe_ratio: float
    profit_factor: float
    avg_trade_pnl: float
    avg_win: float
    avg_loss: float
    total_fees: float
    total_slippage: float
    trades: list[BacktestTrade] = field(default_factory=list)

    @property
    def expectancy(self) -> float:
        """Expected value per trade."""
        if self.total_trades == 0:
            return 0.0
        return self.total_pnl / self.total_trades
